### ISSUE TITLE
appservice traceback

### ISSUE THREAD

**Issue by abma** [TurBoss/matrix-spring-appservice#2]
Jun 25 04:05:18 spring1 sappservice[9975]: [2021-06-25 04:05:18,205] [ERROR@mautrix_appservice] Exception in Matrix event handler
Jun 25 04:05:18 spring1 sappservice[9975]: Traceback (most recent call last):
Jun 25 04:05:18 spring1 sappservice[9975]:   File "/home/matrix/venvs/appservice_38/lib/python3.7/site-packages/mautrix/appservice/as_handler.py", line 178, in try_handle
Jun 25 04:05:18 spring1 sappservice[9975]:     await handler_func(event)
Jun 25 04:05:18 spring1 sappservice[9975]:   File "/home/matrix/apps/appservice/matrix-spring-appservice/sappservice/sappservice.py", line 125, in handle_event
Jun 25 04:05:18 spring1 sappservice[9975]:     await self.handle_message(event.room_id, event.sender, event.content, event.event_id)
Jun 25 04:05:18 spring1 sappservice[9975]:   File "/home/matrix/apps/appservice/matrix-spring-appservice/sappservice/sappservice.py", line 67, in handle_message
Jun 25 04:05:18 spring1 sappservice[9975]:     await self.sl.say_from_matrix(user_id, room_id, event_id, message.body)
Jun 25 04:05:18 spring1 sappservice[9975]:   File "/home/matrix/apps/appservice/matrix-spring-appservice/sappservice/spring_lobby_client.py", line 450, in say_from_matrix
Jun 25 04:05:18 spring1 sappservice[9975]:     room_name = list(v.get('name') for _, v in self.rooms.items() if v.get('room_id') == room_id)[0]
Jun 25 04:05:18 spring1 sappservice[9975]: IndexError: list index out of range

**Comment by abma** [comment]
systemctl restart appservice seems to (temp) fix the issue

**Comment by abma** [comment]
i guess some initial error is triggering this, sadly the log was already truncated. it try to get it with

$ journalctl -u appservice

**Comment by TurBoss** [comment]
thanks for the report, Taking a look
